### ISSUE TITLE
[FEATURE] Housekeeping - Rename to SampleCode

### ISSUE THREAD

**Issue by mvk-abs** [dxfrontier/projen-template-github-action#106]
### Description

Atm the sample code is provided by the SampleComponent. To improve clarity we rename it to SampleCodeComponent.

### Task List

- [x] Adjust naming and imports
- [x] Exec `projen build`
- [x] Test real life project

**Comment by mvk-abs** [comment]
real life tests failed
