### ISSUE TITLE
[FEATURE] Housekeeping - add constants

### ISSUE THREAD

**Issue by mvk-abs** [dxfrontier/projen-template-github-action#22]
### Description

Using constants improves code readability, reduces errors from hard-coded values, and makes updates easier across the codebase.

### Task List

- [x] Add constants module
- [x] Replace GitHubBuilder literals with contstants
- [x] Replace DevContainerBuilder with constants
