### ISSUE TITLE
[FEATURE]  Housekeeping - Husky

### ISSUE THREAD

**Issue by mvk-abs** [dxfrontier/projen-template-github-action#41]
### Description

Enables automated checks on Git hooks, ensuring code quality and consistency before changes are committed.

### Task List

- [x] Add tests
- [x] Add husky files
- [x] Add package.json dependencies
- [x] Check .gitattributes
- [ ] Add husky to .projenrc.ts
