### ISSUE TITLE
[FEATURE] Housekeeping - commitlintc

### ISSUE THREAD

**Issue by mvk-abs** [dxfrontier/projen-template-github-action#42]
### Description

Enforces consistent commit message formats, improving readability and making it easier to track changes.

### Task List

- [x] Add tests
- [x] Add commitlintrc.ts file
- [x] Add package.json dependencies
- [x] Check .gittattributes
- [x] Add commitlinrc.ts to .projenrc.ts
