### ISSUE TITLE
[FEATURE] Housekeeping - prettier

### ISSUE THREAD

**Issue by mvk-abs** [dxfrontier/projen-template-github-action#43]
### Description

Ensures consistent code formatting across the project, enhancing readability and reducing style-related merge conflicts.

### Task List

- [x] Add prettierrc file
- [x] Add prettierignore file
- [x] Add package.json dependencies
- [x] Add prettier to .projenrc.ts

**Comment by mvk-abs** [comment]
forgot to take over the settings

- [ ]  Add prettierrc settings
