### ISSUE TITLE
[FEATURE] Housekeeping - Align .gitattributes linguist-generated

### ISSUE THREAD

**Issue by mvk-abs** [dxfrontier/projen-template-github-action#52]
### Description

Mark files as linguist-generated helps GitHub ignore generated code in language statistics, providing a clearer view of the primary codebase.

### Task List
- [x] Add tests for components checking if .gitattributes was updated
- [x] Add update method to components
- [x] Test with .projenrc.ts

**Comment by mvk-abs** [comment]
now added
/.devcontainer.json linguist-generated
/.npmignore linguist-generated
/.github/ISSUE_TEMPLATE/bug.yml linguist-generated
/.github/ISSUE_TEMPLATE/feature.yml linguist-generated
/.github/ISSUE_TEMPLATE/question.yml linguist-generated
/.vscode/settings.json linguist-generated
/.prettierignore linguist-generated
/.prettierrc.json linguist-generated

still missing as the components are not yet implemented
/.eslintrc.json linguist-generated
/tsconfig.dev.json linguist-generated
/tsconfig.json linguist-generated
