### ISSUE TITLE
[FEATURE] Housekeeping - Standardize 'add scripts' across all builders

### ISSUE THREAD

**Issue by mvk-abs** [dxfrontier/projen-template-github-action#56]
### Description

Ensure consistency and code clarity.

### Task List

- [x] Standardize the 'add scripts' functionality across all builders
- [x] Add test cases when needed

**Comment by mvk-abs** [comment]
Results in a refactoring from builder to component.

**Comment by mvk-abs** [comment]
Forgot to test .projenrc.ts.
- [ ] Add to .projenrc.ts
