### ISSUE TITLE
[FEATURE] Housekeeping - Update .npmignore for components

### ISSUE THREAD

**Issue by mvk-abs** [dxfrontier/projen-template-github-action#60]
### Description

Adding files to .npmignore helps reduce package size and excludes unnecessary files from published npm packages, improving efficiency.

### Task List

- [x] Add tests for components checking if .npmignore was updated
- [x] Add update method to components
- [x] Test with .projenrc.ts

**Comment by mvk-abs** [comment]
NPM ignore seems to be covered by standard. Use the files area of the package.json to define, which files are relevant.
